[workspace]
members = ["core", "terminal", "sftp"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/wfu-work/xssh-rust-lib"

[workspace.dependencies]
russh = { version = "=0.54.3", default-features = false, features = ["ring"] }
tokio = { version = "1", features = ["net", "rt", "time"] }
zeroize = "1.8.1"
russh-sftp = "=2.1.0"
